src/accounts/urls.py
from django.urls import path
from accounts.views import login_user, logout_user, register_user

app_name = 'accounts'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

]

src/image_app/urls.py
from django.urls import path
from image_app.views import check, profile, experiment

app_name = 'image_app'

urlpatterns = [
    path('', check, name='check'),
    path('profile/', profile, name='profile'),
    path('experiment/', experiment, name='experiment'),

]

src/media_service/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_app.urls', namespace='image_app')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/image_app/models.py
from django.db.models import \
    (Model, ImageField, DateTimeField, ForeignKey, IntegerField, CASCADE, DO_NOTHING)
from django.db import models
from media_service.settings import AUTH_USER_MODEL
from django.conf import settings

User = settings.AUTH_USER_MODEL




class ImageStorage(Model):

    user = ForeignKey(User, on_delete=CASCADE, related_name='images_created')
    image = ImageField(upload_to='images/%Y/%m/%d', blank=True, verbose_name='Изображение')
    timestamp = DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Хранилище изоборажений'
        verbose_name_plural = 'Хранилище изоборажений'


    def __str__(self):
        output = str(self.image).split('/')[-1]
        return output

    def __repr__(self):
        output = str(self.image).split('/')[-1]
        return output



class History(Model):

    CAUSE_CHOICES = (
        (1, 'Изображение создано'),
        (2, 'Изображение изменено'),
        (3, 'Изображение удалено'),
    )

    image = ForeignKey(ImageStorage, on_delete=DO_NOTHING, related_name='history')
    cause = IntegerField(choices=CAUSE_CHOICES)# get_cause_display()
    timestamp = DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'История изменений'
        verbose_name_plural = 'История изменений'


    def __str__(self):
        return str(self.timestamp)


"""Валидацию размера изображения можно попытаться сделать в формах clean_ , или в валидаторах"""


"""
ЗАДАНИЕ
Создать одностраничный сайт на Django 3
СО страницы можно отправить картинку на сервер в папку 'media' асинхронно (без перезагрузки).
Максимальный размер файла ограничивается django и составляет 2 Mb. 
Отправить может только зарегистрированный пользователь (зарегистрироваться должен самостоятельно). 
После загрузки файла в базу данных (любая совместимая СУБД) в таблицу записывается 
3 отдельных поля: логин пользователя, дата-время записи и путь к загруженному файлу.
После записи в базу на эл. почту пользователя отправляется 
письмо со значениями всех трех полей в теле через точку с запятой.
У пользователя должен быть личный кабинет, в котором можно перезагрузить любую из загруженных им картинок.
Должна быть возможность посмотреть историю изменений каждого изображения
"""

# 1 создать личный кабинет
# 2 вывести все сохраненные изображения пользователя
# 3 вывести историю изменений этих изображения
# 4 сделать чтобы их можно было менять прямо от туда
# 5 сделать валидатор загрузки изображения в 2 мб
# 6 сделать чтобы при загрузке изображения посылалось письмо

"""СО страницы можно отправить картинку на сервер в папку 'media' асинхронно (без перезагрузки)"""
# Скорее всего это можно сделать только с помощью Ajax



"""
accounts.MyUser
accounts.Profile

image_app.MediaStorage
fields:
- image
- created
- updated
- user (ForeignKey)

"""

src/image_app/forms.py
from django import forms
from image_app.models import ImageStorage



class LoadImageForm(forms.ModelForm):

    class Meta:
        model = ImageStorage
        fields = 'image',
        widgets = {'image': forms.FileInput(attrs={'class': 'form-control',})}

src/image_app/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from image_app.forms import LoadImageForm
from image_app.models import ImageStorage, History

def experiment(request):
    # print('\n'*2,'*'*20, *dir(request), '*'*20, '\n'*2, sep='\n')

    return HttpResponse('CHECK CONSOLE')


def check(request):
    if request.user.is_authenticated:
        if request.POST:
            print(f'\n\n\n{"1 уровень"}\n\n\n')
            form = LoadImageForm(data=request.POST, files=request.FILES)
            if form.is_valid():
                print(f'\n\n\n{"2 уровень"}\n\n\n')
                new_record = form.save(commit=False)
                new_record.user = request.user
                new_record.save()
                History.objects.create(image_id=new_record.id, cause=1)
                return HttpResponse('<p>Файл записан</p><br><a href="http://127.0.0.1:8000/">Назад</a>')
            else:
                print(f'\n\n\n{"3 уровень"}\n\n\n')
                return HttpResponse('<p>ERROR</p><br><a href="http://127.0.0.1:8000/">Назад</a>')
        else:
            print(f'\n\n\n{"4 уровень"}\n\n\n')
            return render(request, template_name='image_app/home.html', context={'form': LoadImageForm()})
    else:
        return redirect(reverse('accounts:login'))






def profile(request):
    user = request.user
    image_list = ImageStorage.objects.filter(user=user)
    history_list = History.objects.filter(image__user=user).select_related('image')
    context = {
        'image_list': image_list,
        'history_list': history_list,
    }
    return render(request, 'image_app/profile.html', context=context)


"""
check
clean
clean_fields
date_error_message
delete
diff_against
from_db
full_clean
get_default_history_user
get_deferred_fields
get_history_type_display
get_next_by_history_date
get_next_by_timestamp
get_previous_by_history_date
get_previous_by_timestamp
history_change_reason
history_date
history_id
history_object
history_type
history_user
history_user_id
id
image
instance
instance_type
next_record
objects
pk
prepare_database_save
prev_record
refresh_from_db
revert_url
save
save_base
serializable_value
timestamp
unique_error_message
user
user_id
validate_unique
"""



# Create your views here.

src/image_app/templates/image_app/home.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6 mx-auto">
        <form method="post" action="{% url 'image_app:check' %}" enctype="multipart/form-data">
            {% csrf_token %}


                {{form.media}}
                {{form.image}}


            <button class="btn btn-primary" type="submit">Отправить</button>
        </form>
    </div>
</div>

<!--<div class="mb-3">-->
<!--    <label for="formFile" class="form-label">Default file input example</label>-->
<!--    <input class="form-control" type="file" id="formFile">-->
<!--</div>-->
{% endblock %}

src/image_app/templates/image_app/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Личный кабинет{% endblock %}

{% block content %}

<div class="col-lg-10">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ID в db</th>
            <th scope="col">Изображение</th>
            <th scope="col">Путь в приложении</th>
            <th scope="col">Изменить</th>
            <th scope="col">Удалить</th>
            <!--            <th scope="col">История</th>-->
        </tr>
        </thead>
        <tbody>
        {% for obj in image_list %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{obj.pk}}</td>
            <td>
                <div class="mn-img">
                    <img src="{{ obj.image.url }}" width="40" height="55" alt="lorem"/>
                </div>
            </td>

            <td>{{obj.image}}</td>
            <td><a href="#">Изменить</a></td>
            <td><a href="#">Удалить</a></td>
        </tr>
        {% endfor %}
        <!--        <tr>-->
        <!--            <th scope="row">2</th>-->
        <!--            <td>Jacob</td>-->
        <!--            <td>Thornton</td>-->
        <!--            <td>@fat</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <th scope="row">3</th>-->
        <!--            <td colspan="2">Larry the Bird</td>-->
        <!--            <td>@twitter</td>-->
        <!--        </tr>-->
        </tbody>
    </table>
</div>
<div class="col-lg-3">
    <table class="table table-success table-striped table-sm">
        <thead>
        <tr>
            <th scope="row">Мои действия</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>some action</td>
        </tr>
        <tr>
            <td>some action</td>
        </tr>
        <tr>
            <td>some action</td>
        </tr>
        <tr>
            <td>some action</td>
        </tr>
        </tbody>
    </table>
</div>


{% endblock %}